### ISSUE TITLE
Error: no lexer for alias 'swift' found

### ISSUE THREAD

**Issue by rivaldid** [gpoore/minted#140]
It's not working with swift code?

**Comment by NobbZ** [comment]
Please update your pygments installation, as far as I understand the bugtracker, the [swift-related](https://bitbucket.org/birkenfeld/pygments-main/issues/1000/swift-programming-language-support) issue is resolved, as well as the linked [track for releases](https://bitbucket.org/birkenfeld/pygments-main/issues/1007/release-new-version) issue.

I'd guess you need at least pygments 2.0 to have swift support available.

**Comment by rivaldid** [comment]
I partially fixed with the package python2-pygments-markdown-lexer, I'm on CentOs. I still having trouble by the way:
pygmentize -l swift prova1/prova1/ValueAdvancedViewController.swift
Traceback (most recent call last):
  File "/usr/bin/pygmentize", line 9, in <module>
    load_entry_point('Pygments==1.4', 'console_scripts', 'pygmentize')()
  File "/usr/lib/python2.7/site-packages/pygments/cmdline.py", line 350, in main
    lexer = get_lexer_by_name(lexer, **parsed_opts)
  File "/usr/lib/python2.7/site-packages/pygments/lexers/__init__.py", line 77, in get_lexer_by_name
    for cls in find_plugin_lexers():
  File "/usr/lib/python2.7/site-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2259, in load
    if require: self.require(env, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2272, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer)))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (Pygments 1.4 (/usr/lib/python2.7/site-packages), Requirement.parse('Pygments>=2.0'))
I will try to update my pygments and will give you feedback.
Regards.

**Comment by NobbZ** [comment]
It seems as if there is no pygments 2.0 available for any centOS. Please install via `pip` or `pypi` or from source.

More detailed information is available at http://pygments.org/.
