### ISSUE TITLE
UnicodeDecodeError with lualatex

### ISSUE THREAD

**Issue by guiniol** [gpoore/minted#95]
Hello,

I have a problem somewhere between `lualatex`, `pygments` and `minted`. Not sure if this is the right place.

I have a minimal working example (below) using `minted`. I can compile it with `xelatex` without trouble, my friend can compile it with `lualatex`, but I cannot compile it with `lualatex`. The really weird thing is, last week I could compile it with `lualatex`. We checked and our installs are mostly the same (same distro, up to date, and the only difference in tex and python related packages do not seem related to minted or encoding; the only candidate was `python-unidecode`, but removing it didn't change anything).

There seems to be an encoding problem. Any idea what could be causing this? How would I go about troubleshooting this?

Here is the error, by what I assume is pygmentize:

```
(./_minted-mwe/default-pyg-prefix.pygstyle) (./mwe.nav)Traceback (most recent call last):
  File "/usr/bin/pygmentize", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3143, in <module>
    @_call_aside
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3129, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3156, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 649, in _build_master
    ws = cls()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 642, in __init__
    self.add_entry(entry)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 698, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2136, in find_on_path
    path_item, entry, metadata, precedence=DEVELOP_DIST
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2518, in from_location
    version = cls._version_from_metadata(dist_path) or version
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2841, in _version_from_metadata
    return _version_from_file(strm)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2483, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 116: ordinal not in range(128)
```

The MWE:

```latex
\documentclass{beamer}

\usepackage{minted}

\begin{document}

\begin{minted}{latex}
	\begin{document}
\end{minted}

\end{document}
```

**Comment by guiniol** [comment]
By the way, I tried setting the `encoding` and `outencoding` options, but it doesn't seem to do anything, it's always the `ascii` codec giving an error.

**Comment by gpoore** [comment]
The error is coming out of `pkg_resources`, which is part of `setuptools`. It's possible that something is wrong with the Pygments installation; you might remove it, then reinstall. Otherwise, there is probably another Python-related issue.

**Comment by guiniol** [comment]
@gpoore Thanks. There was  a setuptools update and now it works.
Thanks a lot, and sorry for the noise.
